RA-14 add seekbar
miroks404/RecieptsApp pull request #14
Opened 2024-12-25 16:17 UTC by miroks404

2024-12-25 16:42 UTC, miroks404 commented
Последним коммитом решил передавать весь класс category через parcelable (с экрана категорий на экран рецептов)

2024-12-25 19:36 UTC, Churickoid requested changes

2024-12-25 19:36 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:max="4" />
Давай установим min, progress параметры, как ты сделал для max. Тогда не придется прибавлять эту непонятную магическую единичку в адаптере

2024-12-25 19:36 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/IngredientsAdapter.kt
> +            "${ingredient.quantity.toDouble() * quantity} ${ingredient.unitOfMeasure}"
Вообще для чисел с точкой лучше использовать BigDecimal. Он позволяет точнее сравнивать и производить вычисления. Плюс есть встроенные методы для форматирования строк. Статья про BigDecimal: https://javarush.com/groups/posts/2274-kak-ispoljhzovatjh-bigdecimal-v-java

val totalQuantity = BigDecimal(ingredientCurrentCount) * BigDecimal(quantity)

val displayQuantity = totalQuantity
.setScale(1,RoundingMode.HALF_UP)
.stripTrailingZeros()
.toPlainString()

2024-12-27 09:25 UTC, Churickoid approved these changes
Молодец, в целом всё верно! Поправь пару мелких комментов в следующем ПР

2024-12-27 09:25 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/IngredientsAdapter.kt
> +                totalQuantity.setScale(1, RoundingMode.HALF_UP).stripTrailingZeros().toPlainString()
Лучше вынести это в отдельную переменную и назвать её понятно, чтобы повысить читаемость кода

2024-12-27 09:25 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
>                  android:max="4" />
по заданию от 1 до 5 у нас порции, сейчас они до 4

2024-12-27 14:13 UTC, merged