RA-16 add favorite button
miroks404/RecieptsApp pull request #16
Opened 2024-12-28 18:41 UTC by miroks404

2024-12-29 17:51 UTC, Churickoid requested changes

2024-12-29 17:51 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/RecipeFragment.kt
> +            binding.ibFavorite.setImageDrawable(
Должна быть логика переключателя. При повторном нажатии должен снова возвращатсья в исходное состояние с пустой иконкой

2025-01-16 08:48 UTC, Churickoid requested changes

2025-01-16 08:48 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/RecipeFragment.kt
> +                            R.drawable.ic_favorite
Условие if (isFavorite) лучше перенести внутрь ContextCompat.getDrawable(), чтобы оно меняло только id drawable. Сейчас очень много повторяющихся строк

2025-01-16 08:48 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/RecipeFragment.kt
> +            seekBar.thumbOffset = -1
Все неизменяемые параметры вьюх лучше писать в xml файле

2025-01-16 08:48 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:layout_height="40dp"
Вынести в ресурсы

2025-01-17 16:36 UTC, ievetrov approved these changes

2025-01-17 16:36 UTC, ievetrov commented on app/src/main/java/ru/miroks404/recieptsapp/RecipeFragment.kt
> +                ibFavorite.setImageResource(if (isFavorite) R.drawable.ic_favorite else R.drawable.ic_heart)
В целом все корректно, но почему иконка скачет при перекраске? Видимо они отличаются размером, нужно перепроверить этот момент.

2025-01-17 16:36 UTC, ievetrov commented on app/src/main/java/ru/miroks404/recieptsapp/RecipeFragment.kt
> +            tvPortionQuantity.text = "1"
Значение по умолчанию для порций (1) можно не задавать отдельной строкой, а прописать прямо в разметке у элемента.

2025-01-17 20:32 UTC, miroks404 commented on app/src/main/java/ru/miroks404/recieptsapp/RecipeFragment.kt
> +                ibFavorite.setImageResource(if (isFavorite) R.drawable.ic_favorite else R.drawable.ic_heart)
это фича)

2025-01-17 20:38 UTC, merged