RA-03 buttons
miroks404/RecieptsApp pull request #3
Opened 2024-11-06 15:28 UTC by miroks404

2024-11-06 15:30 UTC, miroks404 commented
Чуть чуть не понял задания "Размеры основного отступа и половины от основного отступа (в ресурсный файл dimens.xml)."
Не нашел как окрасить иконки статус бара в свой цвет (только программно (через код))
Ну и у меня не запускается приложение( Это нормально на данном этапе?

2024-11-06 21:28 UTC, Churickoid requested changes
Задание можно считать выполненым, если твои кнопки будут соответствовать дизайну из макета фигмы. Как минимум не хватает правильны[ цветов у кнопок.

По поводу размеров основных отступов. Как правило в макетах есть самые популярные размеры, которых подавляющее большинство в макете. Их интуитивно можно увидеть и выделить в отдельный ресурс. Например, у нас очень часто встречается расстояние 16dp по бокам экрана или между карточек. Так вот этот размер можно назвать main_space_16. А половину от него, например, так main_space_half_8. Это будет красиво и единообразно.

Иконки статус бара по заданию красить не надо, только Buttons.

В комментах оставил как починить приложение, чтоб оно запускалось.

Еще нужно удалить папку ui.themes рядом с файлом MainActivity. Это остатки от неправильной генерации проекта

2024-11-06 21:28 UTC, aGroupoid commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.RecieptsApp" parent="android:Theme.Material.Light.NoActionBar" >
То что у тебя не запускается приложение - не нормально. Основная проблема это из-за того, что в AndroidManifest у твоего activity прописан android:exported="false". В манифесте мы указываем все системные компоненты приложения, а также все точки входа для системы Андроид. У activity прописано, что оно является стартовым, то есть при нажатии на иконку система войдёт в приложение через это Activity. Но android:exported="false" говорит системе, что это внутренний компонент, который нельзя запускать из системы, из-за этого ничего не происходит. Нужно установить android:exported="true"

Далее, если ты после исправления попытаешься зайти, в Logcat внутри Android Studio напишет причину падения приложения красными буквами FATAL EXCEPTION: main и в каком конкретно месте это произошло. Ошибка специфическая в данном случае, тебе мало что она скажет. Падение связано с тем, что ты прописал parent="android:Theme.Material.Light.NoActionBar". Это очень древняя тема, она не подходит для текущих Activity, которые эволюционировали в AppCompatActivity. 
Используй актуальноую тему MaterialDesign3:
parent="Theme.Material3.DayNight.NoActionBar"

После этих исправлений приложение должно запускаться

2024-11-06 21:28 UTC, aGroupoid commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="36dp"
Если ты ограничиваешь layout по длине, то и смысл длины wrap_content пропадает, layout обрежет кнопки если они не будут умещаться. Здесь тоже нужно прописать wrap_content, чтоб верстка корректно адаптировалась под контент кнопок

2024-11-06 21:28 UTC, aGroupoid commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="328dp"
В задании  прописано, что кнопки должны быть адаптивны по всей длине. Это значит, что на любом экране кнпоки должны занимать всё пространство по ширине и при этом быть равными. Этого можно добится разными способами. Например, прописать здесь match_parent, кнопкам ширину 0dp и связать их между собой для первой app:layout_constraintStart_toEndOf = "айди второй кнопки" и  для второй кнопки app:layout_constraintEnd_toStartOf ="айди первой кнопки"

2024-11-06 21:28 UTC, aGroupoid commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="4dp"
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки.
Это размер, мы его выносим в dimens, по аналогии со строками и цветами в соседних файлах

2024-11-06 21:28 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/button2"
Нейминг id непонятный, а если кнопок станет 10, как мы будем их различать? Нужно давать более осмысленные названия например buttonCategory

2024-11-06 21:28 UTC, aGroupoid commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginEnd="4dp"
В ресурсы

2024-11-06 21:28 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +            android:drawablePadding="12dp"
В ресурсы

2024-11-06 21:28 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
В styles файлах работает такое же правило, все цвета, строки, dimens тоже выносим в ресурсы и ссылаемся на них

2024-11-06 21:28 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <item name="cornerRadius">8dp</item>
В ресурсы

2024-11-08 19:35 UTC, Churickoid approved these changes
Молодец! Всё верно! Поправь один небольшой коммент в следующем ПР уже

2024-11-08 19:35 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/montserrat_alternates_regular</item>
Поменяй шрифт на более плотный, сейчас не соответсвует толщине букв из дизайна

2024-11-09 20:52 UTC, merged