RA-04 add fragment categories
miroks404/RecieptsApp pull request #4
Opened 2024-11-09 21:43 UTC by miroks404

2024-11-10 18:37 UTC, aGroupoid requested changes

2024-11-10 18:37 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/CategoriesListFragment.kt
> +
Поскольку жизненный цикл фрагмента длиннее, чем у view внутри него, рекомендуется очищать binding в методе onDestroyView.
Подробнее можно почитать здесь: https://developer.android.com/topic/libraries/view-binding#fragments

2024-11-10 18:37 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/MainActivity.kt
> +        fragmentTransaction.commit()
Сейчас никакой фрагмент не кладется в фрагментКотнейнер. Не хватает add.
Но предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). То есть вся магия должна происходить в одной лямбде. Именно для импорта этого метода и метода add() нужно было имплементировать библиотеку fragment-ktx.

Одним из преимуществ этого метода является то, что мы просто указываем тип нового фрагмента, а не передаем экземпляр.

2024-11-11 14:06 UTC, miroks404 commented
Возможно чуть чуть не понял как без использования экземпляра использовать add

2024-11-11 20:32 UTC, aGroupoid commented
Ты верно добавил add, только всё равно внутри commit описан устаревший подход добавления фрагмента. По итогу commit никакого смысла не несет. Почитай внимательно документацию, ссылка на конкретный заголовок. Там всё подробно описано как и почему
https://developer.android.com/guide/fragments/create?hl=ru#add-programmatic

2024-11-12 10:38 UTC, miroks404 commented
Все, сорян, понял!!!

2024-11-12 16:43 UTC, Churickoid approved these changes
Всё верно, молодец! При выполнении следующего задания, ответь на этот коммент

2024-11-12 16:43 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/MainActivity.kt
> +        if (_binding == null)
Что в итоге символизирует эта проверка? Также студия подсвечивает, что это условие всегда true

2024-11-13 15:37 UTC, miroks404 commented on app/src/main/java/ru/miroks404/recieptsapp/MainActivity.kt
> +        if (_binding == null)
хех, да, мы ж добавили проверку на null :)

2024-11-13 15:38 UTC, merged