RA-05 add new fragment
miroks404/RecieptsApp pull request #5
Opened 2024-11-13 16:13 UTC by miroks404

2024-11-14 13:24 UTC, Churickoid requested changes

2024-11-14 13:24 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/MainActivity.kt
> +                replace(R.id.containerMain, CategoriesListFragment())
Давай использовать более новый подход как с методом add, через дженерик

2024-11-14 13:24 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/MainActivity.kt
> +                setReorderingAllowed(true)
В лямбды с транзакциями давай еще добавлять addToBackStack(null). Эта штука позволяет собирать фрагменты в стек, чтобы потом при многократном нажатии кнопки назад был пройден тот же путь. Только обратно. Когда будем внедрять Jetpack Navigation – оно будет там работать уже под капотом.

2024-11-14 13:24 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/MainActivity.kt
> +            add<CategoriesListFragment>(R.id.containerMain)
Перейди на экран Избранного и переверни ориентацию. Произойдет пересоздания Activity, заново вызовется onCreate и твой экран заменится на новый. Такое поведение может плохо сказаться на пользовательском опыте. В нашем случае достаточно класть первый фрагмент только при самом первом запуске. Первый запуск можно проверить по условию if(savedInstanceState == null), это гооворит, что activity ничего не сохранял, значит запуск был первый

2024-11-14 18:02 UTC, Churickoid requested changes

2024-11-14 18:02 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/FavoritesFragment.kt
> +        _binding = ActivityMainBinding.inflate(layoutInflater)
Верстка фрагментов не отображается. .Это связано с тем, что ты во фрагментах прописываешь ActivityMainBinding, а не Fragment...Binding. Поправь на обоях фрагментах, должно заработать

2024-11-15 14:49 UTC, miroks404 commented
использовал все таки replace, т.к при add фрагменты накладываются друг на друга

2024-11-15 18:02 UTC, Churickoid reviewed
По текущему заданию вопросов нет, молодец!
Про repalce ты меня немного не правильно понял, у него есть такая же реализация `replace<MyFragment>(...)` как ту которую ты используешь у `add<>`, конструкция с треугольными скобками называется Дженерик, можешь поискать в инете про неё подробнее. Поправь при выполнении следующего задания это

2024-11-16 01:14 UTC, merged