RA-07 add RecyclerView
miroks404/RecieptsApp pull request #7
Opened 2024-11-16 23:20 UTC by miroks404

В fragment_list_categories.xml для ImageView использовал fitXY чтобы картинка отображалась без отступов справа и слева (пожертвовав качеством)

2024-11-17 18:27 UTC, Churickoid commented
Карточку надо сверстать. Представь, что элемент списка – это вот весь данный лейаут. Сделай для него верстку, заполни тестовыми данными в качестве картинки, названия и описания через атрибуты tools.
В итоге дизайн этого списка должен быть как на макете фигма. Только с одинаковыми тестовыми данными
![image](https://github.com/user-attachments/assets/3805404c-8f5d-48fc-962e-a91d777f5fa4)

2024-11-17 18:30 UTC, Churickoid requested changes

2024-11-17 18:30 UTC, Churickoid commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:scaleType="fitXY"
Давай использовать  лучше centerCrop. Там качество всегда будет нормальным, просто фото немного обрезано будет

2024-11-17 18:30 UTC, Churickoid commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:layout_height="224dp">
Этот параметр тоже нужно вынести в ресурсы. Все такие значения мы выносим в dimens по аналогии с файлами сolors и strings

2024-11-17 18:30 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +    android:layout_height="match_parent"
wrap_content

2024-11-19 02:00 UTC, miroks404 commented
Не добавлял строки, стиль и т.д. так как это пример.
Есть вариант (рисунок 1) который я залил щас (не соблюдаются отступы между карточками) и есть с отступами как в макете в figma (рисунок 2), но картинка не на всю карточку (для этого варианта переходим в item_category.xml, layout width карточки ставим на match_parent и в constraint width ставим на match_parent) 
![image](https://github.com/user-attachments/assets/826e1723-0dc7-4713-921a-1fbc6c26fab8)
![image](https://github.com/user-attachments/assets/e96e041c-db63-4860-9f17-f26e5c5a62c4)

2024-11-19 02:01 UTC, miroks404 commented
Щас так подумал, скорее 2 вариант правильнее :)))

2024-11-19 08:37 UTC, Churickoid commented
Второй вариант верный, но фото внутри карточки должно быть по её ширине полностью

2024-11-19 22:30 UTC, Churickoid approved these changes
Молодец, всё верно сделал! Я здесь ставлю апрув, в системе сайта отправил на доработку. На сайте стоит RA-08, а здесь RA-07. Надо синкануться по заданиям, если какие-то проблемы нерешенные - напиши в личку

2024-11-19 22:30 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="130dp"
Это бы тоже вынести в ресурсы

2024-11-22 14:03 UTC, merged