RA-08 rv adapter
miroks404/RecieptsApp pull request #8
Opened 2024-11-22 17:20 UTC by miroks404

2024-11-22 22:48 UTC, Churickoid requested changes
При нажатии на элементы списка - нет никакого эффекта. Добавь cardView эти параметры, чтоб появился ripple
https://gist.github.com/mrsid96/1ec250e793ad914de27722bdda52e0b1

2024-11-22 22:48 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/CategoryListAdapter.kt
> +        return ViewHolder(view)
Давай перепишем создание с использованием binding, в RecyclerView.ViewHolder передавать binding.root

2024-11-22 22:48 UTC, Churickoid commented on app/src/main/java/ru/miroks404/recieptsapp/CategoryListAdapter.kt
> +
Надо еще добавить “описание контента”. contentDescription используется для предоставления текстового описания для не текстовых элементов, таких как изображения, кнопки с иконками и других графических объектов.
Это происходит так: пользователь водит пальцем по экрану и в зависимости от того, где сейчас активно нажатие – происходит озвучивание. Чтобы перейти в конкретную категорию пользователю нужно совершить двойное нажатие в качестве подтверждения перехода на соответствующую категорию.

Для нединамических фото, достаточно прописать в XML imageView.
Для карточек, менять его в адаптере. Можно задавать картинкам категорий что-то "Изображение категории название_категории".

2024-11-23 02:21 UTC, miroks404 commented
Добавил для tvCategoryDescription padding и убрал margin, так как при margin текст мог чуть чуть выходить за рамки контейнера, как ни химичил, результат был тот же, зато при padding когда текст был ближе к границе чем на 8dp, он сразу переносится, а при margin может и выехать за пределы

2024-11-23 23:00 UTC, aGroupoid approved these changes
Молодец, всё верно!

2024-11-24 22:01 UTC, merged